#!/bin/bash
# 手动安装Playwright浏览器的脚本

echo "=========================================="
echo "Playwright浏览器手动安装指南"
echo "=========================================="
echo ""
echo "由于网络问题，自动安装失败。请按以下步骤手动安装："
echo ""
echo "方法1：使用代理重试"
echo "  export HTTP_PROXY=http://your-proxy:port"
echo "  export HTTPS_PROXY=http://your-proxy:port"
echo "  cd /Users/mac/frontend/code/1.operations/auto-deal-eth"
echo "  source venv/bin/activate"
echo "  playwright install chromium"
echo ""
echo "方法2：手动下载浏览器"
echo "  1. 访问: https://github.com/microsoft/playwright/releases"
echo "  2. 下载对应版本的Chromium"
echo "  3. 解压到: ~/Library/Caches/ms-playwright/chromium_headless_shell-1208/"
echo ""
echo "方法3：稍后重试（网络恢复后）"
echo "  cd /Users/mac/frontend/code/1.operations/auto-deal-eth"
echo "  source venv/bin/activate"
echo "  playwright install chromium"
echo ""
echo "当前需要的浏览器版本："
echo "  Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208)"
echo "  下载地址: https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/mac-x64/chrome-headless-shell-mac-x64.zip"
echo ""
